# MLB Data Set Descriptive Analysis

### Import Libraries

In [22]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

### Import Dataframe

In [25]:
# MLB Dataframe

mlbdf = pd.read_csv(r'C:\Users\cschw\OneDrive\Desktop\MLB Project\Data Sets\MLB Master Data One Tab.csv')

### Check Column Types

In [28]:
# Check types
mlbdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 93 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       300 non-null    int64
 1   Team                       300 non-null    object
 2   W                          300 non-null    int64
 3   L                          300 non-null    int64
 4   W-L%                       300 non-null    float64
 5   R                          300 non-null    float64
 6   RA                         300 non-null    float64
 7   Rdiff                      300 non-null    float64
 8   Home Wins                  300 non-null    int64
 9   Home Losses                300 non-null    int64
 10  Road Wins                  300 non-null    int64
 11  Road Losses                300 non-null    int64
 12  # of Batters               300 non-null    int64
 13  Avg Bat Age                300 non-null    float64
 14  R/G                        300 non-null    float64
 15  G                          300 non-null    int64
 16  PA                         300 non-null    int64
 17  AB                         300 non-null    int64
 18  R.1                        300 non-null    int64
 19  H                          300 non-null    int64
 20  2B                         300 non-null    int64
 21  3B                         300 non-null    int64
 22  HR                         300 non-null    int64
 23  RBI                        300 non-null    int64
 24  SB                         300 non-null    int64
 25  CS                         300 non-null    int64
 26  BB                         300 non-null    int64
 27  SO                         300 non-null    int64
 28  BA                         300 non-null    float64
 29  OBP                        300 non-null    float64
 30  SLG                        300 non-null    float64
 31  OPS                        300 non-null    float64
 32  OPS+                       300 non-null    int64
 33  TB                         300 non-null    int64
 34  GDP                        300 non-null    int64
 35  HBP                        300 non-null    int64
 36  SH                         300 non-null    int64
 37  SF                         300 non-null    int64
 38  IBB                        300 non-null    int64
 39  LOB                        300 non-null    int64
 40  #P                         300 non-null    int64
 41  Avg Pitcher Age            300 non-null    float64
 42  RA/G                       300 non-null    float64
 43  PW                         300 non-null    int64
 44  PL                         300 non-null    int64
 45  PW-L%                      300 non-null    float64
 46  ERA                        300 non-null    float64
 47  G.1                        300 non-null    int64
 48  GS                         300 non-null    int64
 49  GF                         300 non-null    int64
 50  CG                         300 non-null    int64
 51  tSho                       300 non-null    int64
 52  cSho                       300 non-null    int64
 53  SV                         300 non-null    int64
 54  IP                         300 non-null    float64
 55  H.1                        300 non-null    int64
 56  R.2                        300 non-null    int64
 57  ER                         300 non-null    int64
 58  HR.1                       300 non-null    int64
 59  BB.1                       300 non-null    int64
 60  IBB.1                      300 non-null    int64
 61  SO.1                       300 non-null    int64
 62  HBP.1                      300 non-null    int64
 63  BK                         300 non-null    int64
 64  WP                         300 non-null    int64
 65  BF                         300 non-null    int64
 66  ERA+                       300 non-null    int64
 67  FIP                        300 non-null    float64
 68  WHIP                       300 non-null    float64
 69  H9                         300 non-null    float64
 70  HR9                        300 non-null    float64
 71  BB9                        300 non-null    float64
 72  SO9                        300 non-null    float64
 73  SO/W                       300 non-null    float64
 74  LOB.1                      300 non-null    int64
 75  Attendance                 300 non-null    object
 76  Attend/G                   300 non-null    object
 77  BPF                        300 non-null    int64
 78  PPF                        300 non-null    int64
 79  # of All Stars             300 non-null    int64
 80  Cumulative # of All Stars  300 non-null    int64
 81  Est. Payroll               300 non-null    object
 82  Avg Game Time              300 non-null    object
 83  Avg Game Time Min          300 non-null    int64
 84  City                       300 non-null    object
 85  State                      300 non-null    object
 86  League                     300 non-null    object
 87  Division                   300 non-null    object
 88  Region                     300 non-null    object
 89  All Star Rating            270 non-null    float64
 90  All Star Viewers           270 non-null    object
 91  World Series Rating        270 non-null    float64
 92  World Series Viewers       270 non-null    object
dtypes: float64(24), int64(57), object(12)
memory usage: 218.1+ KB

### Exporting Info as CSV

In [45]:
import io

# Capture the output of mlbdf.info()
buffer = io.StringIO()
mlbdf.info(buf=buffer)
info_str = buffer.getvalue()

# Split the captured output into lines and then into lists
info_lines = info_str.splitlines()
info_list = [line.split() for line in info_lines]

# Convert the list into a DataFrame
info_df = pd.DataFrame(info_list)

# Save the DataFrame to a CSV file
info_df.to_csv(r'C:\Users\cschw\OneDrive\Desktop\MLB Project\Data Sets\MLB_Info.csv', index=False, header=False)

### Descriptive Stats

In [31]:
# Set options to display all columns
pd.set_option('display.max_columns', None)

In [33]:
# Descriptive Statistics
mlbdf.describe()

,Year,W,L,W-L%,R,RA,Rdiff,Home Wins,Home Losses,Road Wins,Road Losses,# of Batters,Avg Bat Age,R/G,G,PA,AB,R.1,H,2B,3B,HR,RBI,SB,CS,BB,SO,BA,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,LOB,#P,Avg Pitcher Age,RA/G,PW,PL,PW-L%,ERA,G.1,GS,GF,CG,tSho,cSho,SV,IP,H.1,R.2,ER,HR.1,BB.1,IBB.1,SO.1,HBP.1,BK,WP,BF,ERA+,FIP,WHIP,H9,HR9,BB9,SO9,SO/W,LOB.1,BPF,PPF,# of All Stars,Cumulative # of All Stars,Avg Game Time Min,All Star Rating,World Series Rating
count,300.00000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.00000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,270.000000,270.000000
mean,2019.50000,74.640000,74.640000,0.499980,4.516667,4.518000,-0.003333,39.760000,34.880000,34.880000,39.760000,51.656667,28.165667,4.516167,149.286667,5647.863333,5054.433333,673.056667,1259.820000,250.676667,23.696667,176.593333,642.743333,81.510000,27.653333,472.583333,1251.983333,0.248733,0.318517,0.412897,0.731433,98.086667,2087.670000,107.830000,59.213333,22.820000,36.903333,22.723333,1006.500000,29.980000,28.589333,4.515833,74.640000,74.640000,0.499980,4.225600,149.286667,149.286667,147.593333,1.693333,9.213333,0.840000,37.626667,1325.344667,1259.82000,673.056667,619.936667,176.593333,472.583333,22.723333,1251.983333,59.213333,4.900000,53.310000,5647.853333,102.240000,4.231700,1.308147,8.545333,1.209000,3.230333,8.538000,2.690500,1006.500000,100.060000,100.036667,2.293333,12.413333,181.463333,4.900000,7.888889
std,2.87708,19.724789,19.713934,0.081864,0.483772,0.554829,0.811614,10.476398,10.025332,10.165138,10.619084,6.115837,0.989774,0.482453,30.756316,1186.869995,1065.883460,154.902257,279.981869,60.325639,10.256150,49.392104,148.574444,34.136014,10.284246,112.156945,276.784468,0.012073,0.012846,0.027457,0.038593,9.503343,467.511008,28.211713,18.861788,15.646415,10.848022,13.007078,215.116621,4.941761,1.118088,0.553910,19.724789,19.713934,0.081864,0.559178,30.756316,30.756316,30.501296,1.834076,4.256157,1.038265,10.758241,278.871215,284.83102,159.911033,149.364135,44.017950,109.926989,13.355950,278.065913,16.286969,2.759599,16.982006,1188.014557,12.196924,0.430302,0.098687,0.646171,0.187268,0.417325,0.782131,0.456594,216.121675,4.690031,4.808923,1.700075,3.869418,11.751410,0.848791,2.492566
min,2015.00000,19.000000,17.000000,0.225000,3.000000,3.200000,-2.100000,11.000000,7.000000,6.000000,8.000000,38.000000,25.900000,3.040000,58.000000,2011.000000,1752.000000,219.000000,390.000000,73.000000,3.000000,51.000000,204.000000,14.000000,3.000000,147.000000,440.000000,0.212000,0.277000,0.339000,0.616000,74.000000,650.000000,28.000000,10.000000,0.000000,7.000000,1.000000,337.000000,18.000000,26.100000,3.170000,19.000000,17.000000,0.225000,2.800000,58.000000,58.000000,56.000000,0.000000,0.000000,0.000000,6.000000,473.000000,376.00000,209.000000,181.000000,62.000000,145.000000,0.000000,393.000000,14.000000,0.000000,11.000000,1989.000000,77.000000,3.230000,1.048000,6.900000,0.700000,2.300000,6.500000,1.870000,348.000000,90.000000,91.000000,0.000000,4.000000,152.000000,3.800000,4.700000
25%,2017.00000,67.000000,66.750000,0.438000,4.200000,4.100000,-0.600000,35.000000,30.000000,30.000000,35.000000,48.000000,27.500000,4.187500,162.000000,5979.750000,5356.750000,639.750000,1259.500000,236.000000,17.000000,149.000000,612.000000,57.750000,21.750000,429.500000,1203.000000,0.240750,0.310000,0.394000,0.704000,91.000000,2062.500000,98.000000,48.000000,10.000000,32.000000,12.750000,1014.750000,26.000000,27.800000,4.117500,67.000000,66.750000,0.438000,3.827500,162.000000,162.000000,156.000000,0.000000,6.000000,0.000000,33.000000,1415.750000,1235.50000,626.250000,573.500000,158.750000,439.000000,12.000000,1191.000000,51.000000,3.000000,43.750000,5947.000000,94.000000,3.927500,1.239000,8.100000,1.100000,2.900000,7.900000,2.320000,1013.250000,97.000000,97.000000,1.000000,10.000000,178.750000,4.200000,6.100000
50%,2019.50000,78.000000,76.500000,0.503500,4.500000,4.450000,0.000000,41.000000,36.000000,36.000000,41.000000,51.000000,28.200000,4.480000,162.000000,6095.500000,5476.500000,701.500000,1348.000000,265.500000,23.000000,178.500000,669.500000,79.000000,28.000000,493.500000,1327.000000,0.249000,0.318500,0.412000,0.731000,97.000000,2212.000000,113.000000,58.000000,20.000000,38.000000,20.000000,1080.000000,30.000000,28.600000,4.445000,78.000000,76.500000,0.503500,4.160000,162.000000,162.000000,160.000000,1.000000,9.000000,1.000000,39.000000,1436.100000,1342.00000,698.500000,641.000000,182.000000,491.500000,21.000000,1313.000000,60.000000,4.000000,53.000000,6092.000000,101.000000,4.205000,1.303500,8.500000,1.200000,3.200000,8.600000,2.645000,1074.000000,100.000000,100.000000,2.000000,13.000000,185.000000,5.000000,8.100000
75%,2022.00000,89.000000,88.000000,0.562000,4.800000,4.900000,0.600000,47.000000,42.000000,42.000000,47.000000,55.000000,28.800000,4.800000,162.000000,6196.000000,5534.250000,761.500000,1410.000000,286.250000,30.000000,214.250000,728.500000,103.000000,34.000000,550.750000,1416.250000,0.257000,0.328000,0.431000,0.755000,104.000000,2341.500000,127.000000,71.000000,34.000000,43.000000,32.000000,1120.250000,33.000000,29.300000,4.912500,89.000000,88.000000,0.562000,4.630000,162.000000,162.000000,161.000000,2.000000,12.000000,1.000000,45.000000,1446.125000,1418.00000,772.250000,718.000000,201.250000,540.000000,32.000000,1423.000000,70.000000,7.000000,63.250000,6199.250000,109.250000,4.470000,1.379500,8.925000,1.300000,3.500000,9.000000,3.015000,1120.500000,102.000000,102.000000,3.000000,15.000000,190.000000,5.400000,8.600000
max,2024.00000,111.000000,115.000000,0.717000,5.800000,6.100000,2.300000,60.000000,59.000000,57.000000,62.000000,69.000000,31.400000,5.850000,163.000000,6475.000000,5770.000000,947.000000,1598.000000,355.000000,56.000000,307.000000,916.000000,190.000000,63.000000,656.000000,1654.000000,0.282000,0.352000,0.501000,0.848000,126.000000,2832.000000,160.000000,112.000000,71.000000,69.000000,67.000000,1224.000000,43.000000,31.900000,6.060000,111.000000,115.000000,0.717000,5.840000,163.000000,163.000000,163.000000,11.000000,21.000000,5.000000,62.000000,1489.200000,1617.00000,981.000000,910.000000,305.000000,694.000000,73.000000,1687.000000,110.000000,15.000000,98.000000,6437.000000,146.000000,5.560000,1.601000,10.200000,1.900000,4.400000,11.000000,3.980000,1219.000000,118.000000,118.000000,8.000000,22.000000,205.000000,6.600000,12.900000

### Saving stats as csv

In [35]:
desc_stats = mlbdf.describe()

In [37]:
desc_stats.to_csv(r'C:\Users\cschw\OneDrive\Desktop\MLB Project\Data Sets\Descriptive_Stats.csv')